//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelicopkkiDev.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class AudioModel : global::System.Configuration.ApplicationSettingsBase {
        
        private static AudioModel defaultInstance = ((AudioModel)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AudioModel())));
        
        public static AudioModel Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowsAudioReaction {
            get {
                return ((bool)(this["AllowsAudioReaction"]));
            }
            set {
                this["AllowsAudioReaction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowsCharacterToScaleDance {
            get {
                return ((bool)(this["AllowsCharacterToScaleDance"]));
            }
            set {
                this["AllowsCharacterToScaleDance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowsCharacterToJumpDance {
            get {
                return ((bool)(this["AllowsCharacterToJumpDance"]));
            }
            set {
                this["AllowsCharacterToJumpDance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double CharacterMaxDanceScale {
            get {
                return ((double)(this["CharacterMaxDanceScale"]));
            }
            set {
                this["CharacterMaxDanceScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double CharacterDanceIntensity {
            get {
                return ((double)(this["CharacterDanceIntensity"]));
            }
            set {
                this["CharacterDanceIntensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double AudioVolumeWeight {
            get {
                return ((double)(this["AudioVolumeWeight"]));
            }
            set {
                this["AudioVolumeWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowsCharacterToSpinWithAudio {
            get {
                return ((bool)(this["AllowsCharacterToSpinWithAudio"]));
            }
            set {
                this["AllowsCharacterToSpinWithAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double CharacterSpinSpeed {
            get {
                return ((double)(this["CharacterSpinSpeed"]));
            }
            set {
                this["CharacterSpinSpeed"] = value;
            }
        }
    }
}
