//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelicopkkiDev.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class BasicModel : global::System.Configuration.ApplicationSettingsBase {
        
        private static BasicModel defaultInstance = ((BasicModel)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BasicModel())));
        
        public static BasicModel Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CharacterAngle {
            get {
                return ((double)(this["CharacterAngle"]));
            }
            set {
                this["CharacterAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double CharacterOpacity {
            get {
                return ((double)(this["CharacterOpacity"]));
            }
            set {
                this["CharacterOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double CharacterScaleX {
            get {
                return ((double)(this["CharacterScaleX"]));
            }
            set {
                this["CharacterScaleX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double CharacterGifSpeed {
            get {
                return ((double)(this["CharacterGifSpeed"]));
            }
            set {
                this["CharacterGifSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowsCharacterShadow {
            get {
                return ((bool)(this["ShowsCharacterShadow"]));
            }
            set {
                this["ShowsCharacterShadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("135")]
        public double CharacterShadowDirection {
            get {
                return ((double)(this["CharacterShadowDirection"]));
            }
            set {
                this["CharacterShadowDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CharacterShadowDepth {
            get {
                return ((double)(this["CharacterShadowDepth"]));
            }
            set {
                this["CharacterShadowDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double CharacterShadowRadius {
            get {
                return ((double)(this["CharacterShadowRadius"]));
            }
            set {
                this["CharacterShadowRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double CharacterShadowOpacity {
            get {
                return ((double)(this["CharacterShadowOpacity"]));
            }
            set {
                this["CharacterShadowOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CharacterWindowTopmost {
            get {
                return ((bool)(this["CharacterWindowTopmost"]));
            }
            set {
                this["CharacterWindowTopmost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowsHotMenu {
            get {
                return ((bool)(this["ShowsHotMenu"]));
            }
            set {
                this["ShowsHotMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CharacterPositionX {
            get {
                return ((double)(this["CharacterPositionX"]));
            }
            set {
                this["CharacterPositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CharacterPositionY {
            get {
                return ((double)(this["CharacterPositionY"]));
            }
            set {
                this["CharacterPositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowsFps {
            get {
                return ((bool)(this["ShowsFps"]));
            }
            set {
                this["ShowsFps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double CharacterSizeRatio {
            get {
                return ((double)(this["CharacterSizeRatio"]));
            }
            set {
                this["CharacterSizeRatio"] = value;
            }
        }
    }
}
