//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelicopkkiDev.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class MouseModel : global::System.Configuration.ApplicationSettingsBase {
        
        private static MouseModel defaultInstance = ((MouseModel)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MouseModel())));
        
        public static MouseModel Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowsMouseReaction {
            get {
                return ((bool)(this["AllowsMouseReaction"]));
            }
            set {
                this["AllowsMouseReaction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double CharacterFollowIntensity {
            get {
                return ((double)(this["CharacterFollowIntensity"]));
            }
            set {
                this["CharacterFollowIntensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double CharacterTiltIntensity {
            get {
                return ((double)(this["CharacterTiltIntensity"]));
            }
            set {
                this["CharacterTiltIntensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double CharacterFlipIntensity {
            get {
                return ((double)(this["CharacterFlipIntensity"]));
            }
            set {
                this["CharacterFlipIntensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double CharacterMaxHeadingScale {
            get {
                return ((double)(this["CharacterMaxHeadingScale"]));
            }
            set {
                this["CharacterMaxHeadingScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CharacterEscapeIntensity {
            get {
                return ((double)(this["CharacterEscapeIntensity"]));
            }
            set {
                this["CharacterEscapeIntensity"] = value;
            }
        }
    }
}
